# Generated by Django 3.1 on 2020-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderlist', '0002_query_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.TextField(default='NULL'),
        ),
    ]
