# Generated by Django 3.1 on 2020-08-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderlist', '0003_auto_20200809_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.TextField(),
        ),
    ]
