# Generated by Django 3.1 on 2020-08-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminderlist', '0004_auto_20200809_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
