# Generated by Django 3.1 on 2020-08-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderlist', '0006_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='slug',
            field=models.SlugField(default='max_length=1024'),
            preserve_default=False,
        ),
    ]
