# Generated by Django 3.1 on 2020-08-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminderlist', '0007_todolist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='slug',
        ),
    ]
